config/routes.rb
Rails.application.routes.draw do

  resources :stories do
    resources :votes do
    end
  end
  
  resource :session
    
end

app/models/story.rb
class Story < ActiveRecord::Base
  #correct validations to add in a way to prevent/ remind users that the maximum number of characters in a link is 100
  belongs_to :user
  
  validates :name,  
  presence: true,
  length: {maximum: 100},
  allow_nil: false
  
  validates :link, 
  presence: true,
  length: {maximum: 100},
  allow_nil: false
  
  has_many :votes do
    def latest
      order('id DESC').limit(3)
    end
  
  end
  
  def to_param
    "#{id}-#{name.gsub(/\W/,'-').downcase}"
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :stories
  has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :story
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :current_user
  
  protected
  
  
  def current_user
    return unless session[:user_id]
    @current_user = User.where(id: session[:user_id]).first
  end

  def ensure_login
    return true if logged_in?
    session[:return_to] = request.fullpath
    redirect_to new_session_path and return false
  end

  def logged_in?
    !@current_user.nil?
  end
  helper_method :logged_in?
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @current_user = User.find_by(email: params[:email])
    if @current_user && @current_user.authenticate(params[:password])
      session[:user_id] = @current_user.id
      if session[:return_to]
        redirect_to session[:return_to]
        session[:return_to] = nil
      else
        redirect_to stories_path
      end
    else
      render action: 'new'
    end
  end

  def destroy
    session[:user_id] = @current_user = nil
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :ensure_login, only: [ :new, :create ]
  def index
    @current_time= Time.now
    @story= Story.order('RANDOM()').first
    @story_count= Story.count
  end
  
  def create
     @story = @current_user.stories.build story_params
    if @story.save
      flash[:notice]= 'Story submission succeeded'
      redirect_to stories_path
    else
      render action:'new'
    end
  end
  
  def new
    @story= Story.new
  end
  
  def show
    @story= Story.find(params[:id])
  end
  
  def edit
   @story = Story.find params[:id]
 end

 def update
   @story = Story.find params[:id]
   if @story.update_attributes(story_params)
     render'show'
   else
     render 'edit'
   end
 end
  
  private
  
  def story_params
    params.require(:story).permit(:name, :link)
  end
  
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  
   def create
     @story = Story.find(params[:story_id])
     @story.votes.create(user: @current_user)
     respond_to do |format|
       format.html { redirect_to @story, notice: 'Vote was successfully created.' }
       format.js {}
     end
   end
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Readit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
</head>
<body>
  <div id="content">
     <div id="login_logout">
       <% if @current_user %>
         Logged in as:
         <%= @current_user.name %>
         <em><%= link_to "(Logout)", session_path, method: :delete %></em>
       <% else %>
         <em>Not logged in.</em>
         <%= link_to 'Login', new_session_path %>
       <% end %>
     </div>
     <h1>Readit</h1>
     <% unless flash[:notice].blank? %>
       <div id="notification"><%= flash[:notice] %></div>
     <% end %>
     <div class="container"> <%= yield %> </div>
   </div>

   <ul id="navigation">
     <li><%= link_to 'Front page stories', stories_path %></li>
     <li><%= link_to 'Submit a new story!',new_story_path %></li>
   </ul>
 </div>
  
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

</body>
</html>

app/views/stories/edit.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Update Story</h5>
    <br>
    <br>
      
      <% if @story.errors.any? %>
      <div class="form_errors">
        <h5>Errors</h5>
        <ul>
          <% @story.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
    <%= form_for @story do |f| %>
    <div>
      <%= f.label :name %>
      <%= f.text_field :name, maxlength: 100, size: 30 %>
    </div>
    <div>
      <%= f.label :link %>
      <%= f.text_field :link, maxlength: 100, size: 30 %> 
    </div>
    <%= submit_tag %>
    <% end %>
  </div>
</div>
<br>
<br>
<%= link_to 'View Random Link', stories_path, class: 'btn  btn-primary' %>

app/views/stories/index.html.erb
<p>A random link:<%= link_to @story.name, @story %></p>
<p>Number of votes: <%= @story.votes.size %></p>
<p><%= link_to 'Edit Story', edit_story_path(@story), class: 'btn btn-light' %></p>
<br>
<div id="vote_form">
  <%= form_tag story_votes_path(@story) %>
  <button ="submit" class="btn btn-default"><%= submit_tag 'Vote for story' %></button>
</div>
<br>
<br>
<br>
  <%= link_to 'Add New Story', new_story_path(@story), class: 'btn btn-primary' %>
  <%= link_to 'View Another Random Link', stories_path, class: 'btn  btn-primary' %>
<br>
<p>Total number of stories on Readit: <%= @story_count %><p>

app/views/stories/new.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Create Story</h5>
    <br>
    <br>
      
      <% if @story.errors.any? %>
      <div class="form_errors">
        <h5>Errors</h5>
        <ul>
          <% @story.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
    <%= form_for @story do |f| %>
    <div>
      <%= f.label :name %>
      <%= f.text_field :name, maxlength: 100, size: 30 %>
    </div>
    <div>
      <%= f.label :link %>
      <%= f.text_field :link, maxlength: 100, size: 30 %> 
    </div>
    <%= submit_tag %>
    <% end %>
  </div>
</div>
<br>
<br>
<%= link_to 'View Random Link', stories_path, class: 'btn  btn-primary' %>

app/views/stories/show.html.erb
<h5><%= @story.name %></h5>
<p>Link:<a href="#" class="card-link"><%= link_to @story.link, @story %></a></p>
<br>
<div>
  <%= link_to 'Edit Story', edit_story_path(@story), class: 'btn btn-light' %>
</div>
<br>
<div id="vote_form">
  <%= form_tag story_votes_path(@story) %>
  <button="submit" class="btn btn-default" id="vote_button"><%= submit_tag 'Vote for story' %></button>
</div>
<h2><span id="vote_score">Score: <%= @story.votes.size %></span></h2>
<br>
<br>
<div id="vote_history">
  <% if @story.votes.empty? %>
    <em>No votes yet!</em>
  <% else %>
    <%= render partial: 'votes/vote', collection: @story.votes.latest %> 
  <% end %> 
</div>

<p class="submitted_by"
   Submitted by:
   <span><%= @story.user.name %></span>
 </p>

<br>
<br>
<br>
<%= link_to 'Add New Story', new_story_path(@story), class: 'btn btn-primary' %>
<%= link_to 'View Random Link', stories_path, class: 'btn  btn-primary' %>

app/views/votes/_vote.html.erb
<li><%= vote.created_at.to_formatted_s(:short) %></li>

app/views/votes/create.html.erb
<h1>Votes#create</h1>
<p>Find me in app/views/votes/create.html.erb</p>

app/views/votes/create.js.erb
$("#vote_score").html("Score: " + <%= @story.votes.size %>)
$("#vote_score").css({backgroundColor: "#ffffcc"});

$("#vote_history").html('<%= j( render partial: "votes/vote",
                                       collection: @story.votes.latest )  %>')
setTimeout(function(){
  $("#vote_score").css({backgroundColor: "#ffffff"});
}, 2000);